[project]
name = "aaa-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "pyrad>=2.4",
    "requests>=2.32.3",
    "seaborn>=0.13.2",
]
